/*
 *	Autogenerated code from TrainFramework
 *  Created on: 2019-10-04T11:23:44.389Z
 *      Author: AL
 */

#ifndef TELNET_H_
#define TELNET_H_
typedef struct RailTelnet {
	void *car;
	uint64_t command;
	char *response;
	uint16_t respLen;
	uint16_t respBufLen;
	char **argv;
	uint16_t argc;
	char *respOk;
	char *respErr;
}__attribute__ ((__packed__)) RailTelnet_st;

int telnetStation(void *p);
void telnetStationInit(void);
#endif /* TELNET_H_ */
