/*
 * ble.c
 * Autogenerated code from TrainFramework
 *
 *  Created on: 2019-10-04T07:59:49.427Z
 *      Author: ALex
 */


#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#include "core-train.h"
#include "core-routes.h"
#include "core-utils.h"
#include "RestFullController.h"

#include "tcp.h"
#include "telnet.h"
#include "json.h"
#include "http.h"
#include "files.h"
#include "database.h"
#include "mqtt.h"
#include "udp.h"
#include "snmp.h"
#include "flash.h"
#include "serial.h"
#include "ow.h"
#include "ble.h"


#define DEBUG_TRACE
#ifdef DEBUG_TRACE
	#define TRACE(trace)	do{\
								trace;\
							}while(0)
#else
	#define TRACE(trace)
#endif

static char bleBufTx[128];
static char bleBufRx[128];

static Beacon_st *bTable[64];
static int iTable = 0;
int observe(RailSerial_st *serial, RailBle_st *ble){
	bTable[iTable++] = (Beacon_st*)serial->request;
	return EXIT_SUCCESS;
}

static RailBle_st bleObserver={
	.command = COMMAND_SERIAL_READ_OBSERVER,
	.response = (uint8_t*)bleBufRx,
	.respLen = sizeof(bleBufRx)
};
int parse(RailSerial_st *serial, RailBle_st *ble){
	if(!serial->request) return EXIT_FAILURE;
	if(equals((char*)serial->request,"\r\n",2)) return EXIT_FAILURE;

	sendTrainsFromDepot(ROUTE_BLE,ROUTE_SERIAL,&bleObserver);

	if(!equals((char*)serial->request,"getv",4)){
		restParser(
			(char*)serial->request,
			bleBufRx,
			sizeof(bleBufRx),
			"getv",
			" ",
			(char**)&ble->argv[0],
			&ble->argc,
			4
		);
	}
	else if(!equals((char*)serial->request,"get",3)){
		restParser(
			(char*)serial->request,
			bleBufRx,
			sizeof(bleBufRx),
			"get",
			" ",
			(char**)&ble->argv[0],
			&ble->argc,
			4
		);
	}
	else if(!equals((char*)serial->request,"put",3)){
		restParser(
			(char*)serial->request,
			bleBufRx,
			sizeof(bleBufRx),
			"put",
			" ",
			(char**)&ble->argv[0],
			&ble->argc,
			4
		);
	}
	else
		return EXIT_FAILURE;

	return EXIT_SUCCESS;
}

static Parcel_st bleParcel[2];
static Train_st bleTrain;
static Parcel_st *pBox[2];
void bleStationInit(void){
	fillDepot(&bleTrain);
	bleTrain.box = pBox;
	for(uint16_t iParcel=0;iParcel<2;iParcel++){
		bleTrain.box[iParcel] = (Parcel_st*)&bleParcel[iParcel];
	}
	bleTrain.capacity = 2;
	bleTrain.route = ROUTE_BLE;

	sendTrainsFromDepot(ROUTE_BLE,ROUTE_SERIAL,&bleObserver);

	static RailBle_st bleCmdModeObs;
	bleCmdModeObs.command = COMMAND_SERIAL_SEND;
	bleCmdModeObs.response = (uint8_t*)AT_CMD_SET_MODE_OBSERVER;
	bleCmdModeObs.respLen = sizeof(AT_CMD_SET_MODE_OBSERVER)-1;
	sendTrainsFromDepot(ROUTE_BLE,ROUTE_SERIAL,&bleCmdModeObs);

	static RailBle_st bleCmdRst;
	bleCmdRst.command = COMMAND_SERIAL_SEND;
	bleCmdRst.response = (uint8_t*)AT_CMD_RST;
	bleCmdRst.respLen = sizeof(AT_CMD_RST)-1;
	sendTrainsFromDepot(ROUTE_BLE,ROUTE_SERIAL,&bleCmdRst);

}

int bleStation(void *p){

	uint16_t iBox = meetTrainBox(&bleTrain,0);
	Parcel_st *box = bleTrain.box[iBox];
	while(box){
		if(iBox>bleTrain.capacity) return EXIT_SUCCESS;
		TRACE(printf("BLE\n"););
		static void *car;
		car = box->parcel;
		TRACE(printf("\tserial %I64u\n",((RailSerial_st *)car)->command););
//		for(uint8_t iHitch=0;iHitch<(1-1);iHitch++){
//			
//			car = ((Hitch_st*)car)->car;
//		}

		if(car==NULL) return EXIT_FAILURE;
		
		else if( COMMAND_SERIAL_READ_OBSERVER == ((RailSerial_st *)car)->command ){
			TRACE(printf("\tCOMMAND_SERIAL_READ_OBSERVER\n"););
			
			RailSerial_st *railSerial = ((RailSerial_st *)car);
			
			static RailBle_st railBle_0;

			try( (railSerial), "the rails RailSerial_st do not go to bleStation\n", EXIT_FAILURE );

			
			observe(railSerial,&railBle_0);
			

			
		}
		
		else if( COMMAND_SERIAL_SEND == ((RailSerial_st *)car)->command ){
			TRACE(printf("\tCOMMAND_SERIAL_SEND\n"););
			
			RailSerial_st *railSerial = ((RailSerial_st *)car);
			
			static RailBle_st railBle_1;

			try( (railSerial), "the rails RailSerial_st do not go to bleStation\n", EXIT_FAILURE );

			
			parse(railSerial,&railBle_1);
			

			
		}
		
		

		iBox = meetTrainBox(&bleTrain,iBox);
		box = bleTrain.box[iBox];
	}

	return EXIT_SUCCESS;
}


