/*
 * ow.h
 * Autogenerated code from TrainFramework
 *
 *  Created on: 2019-10-04T07:59:49.432Z
 *      Author: ALex
 */

#ifndef _OW_H_
#define _OW_H_

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#include "core-train.h"
#include "core-routes.h"
#include "core-utils.h"

#include "database.h"
#include "serial.h"

typedef struct {
	uint8_t commandRead[16];
	uint8_t teperature[16];
	uint8_t tHreg[8];
	uint8_t tLreg[8];
	uint8_t confReg[8];
	uint8_t reserved[24];
	uint8_t	crc[8];
} __attribute__ ((__packed__)) scrathpad_t;

typedef struct RailOw{
	void *car;
	uint64_t command;
	uint8_t *response;
	uint16_t respLen;
	uint16_t respBufLen;
	uint8_t *request;
	uint16_t reqLen;
	uint32_t baud;
}__attribute__ ((__packed__)) RailOw_st;


typedef enum {
	ow_start=0,
	ow_measure,
	ow_convert,
	ow_read,
	ow_reset,
	ow_end,
	ow_wait,
	ow_fault
}stateOwreset_t;


#define ONEWIRE_UART_BAUD_LOW	9600

#define ONEWIRE_UART_BAUD_HI	115200


stateOwreset_t getOwState(void);

int owStation(void *p);
void owStationInit(void);

#endif /* _OW_H_ */


